### ISSUE TITLE
weird issue when having more than 500 git blame at once

### ISSUE THREAD

**Issue by malickz** [alessioalex/git-blame#3]
hi, i m trying to get blame data of multiple files at once but the plugin is throwing an exception 
```
Unhandled rejection TypeError: Cannot read property 'on' of undefined
    at readStreamIfy (/Users/***/workspace/angular-cli/test-repo/node_modules/spawn-to-readstream/index.js:23:12)
    at module.exports (/Users/***/workspace/angular-cli/test-repo/node_modules/git-spawned-stream/index.js:17:10)
    at blame (/Users/***/workspace/angular-cli/test-repo/node_modules/git-blame/index.js:29:26)
    at Promise (/Users/***/workspace/angular-cli/test-repo/server/routes/api.js:255:18)
    at Promise._execute (/Users/***/workspace/angular-cli/test-repo/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/***/workspace/angular-cli/test-repo/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/***/workspace/angular-cli/test-repo/node_modules/bluebird/js/release/promise.js:79:10)
    at getBlameData (/Users/***/workspace/angular-cli/test-repo/server/routes/api.js:246:10)
    at Promise.each (/Users/***/workspace/angular-cli/test-repo/server/routes/api.js:131:9)
    at tryCatcher (/Users/***/workspace/angular-cli/test-repo/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/***/workspace/angular-cli/test-repo/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/Users/***/workspace/angular-cli/test-repo/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/***/workspace/angular-cli/test-repo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/***/workspace/angular-cli/test-repo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/***/workspace/angular-cli/test-repo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/***/workspace/angular-cli/test-repo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/***/workspace/angular-cli/test-repo/node_modules/bluebird/js/release/promise.js:693:18)

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn git EAGAIN
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by alessioalex** [comment]
Hey @malickz I think this is not a problem with the module itself, but with the fact that there are a lot of processes opened in the same time. See this thread for example: https://github.com/atom/atom/issues/4692

**Comment by malickz** [comment]
yeah i was exceed the max number of processes, added throttling to the request and its all fine now. thanks @alessioalex
